SELECT  TODAY.ID AS ID
  FROM  WEATHER AS TODAY
 INNER
  JOIN  WEATHER AS YESTERDAY
    ON  DATE_ADD(YESTERDAY.RECORDDATE, INTERVAL 1 DAY) = TODAY.RECORDDATE
 WHERE  TODAY.TEMPERATURE > YESTERDAY.TEMPERATURE